#!/bin/bash
#SBATCH --job-name=mpi
#SBATCH --output=/hkfs/work/workspace/scratch/bg5912-radiosims/magicsims_set04/logs/_log%j.out
#SBATCH --error=/hkfs/work/workspace/scratch/bg5912-radiosims/magicsims_set04/logs/_log%j.err
#SBATCH --nodes=2
#SBATCH --cpus-per-task=12
#SBATCH --time=03:00:00
#SBATCH --tasks=2
######SBATCH --mem=50gb
######SBATCH --export=NONE
#######################SBATCH --gres=gpu:4

/home/hk-project-radiohfi/bg5912/CoreasSpellcaster/corsikaSim.sh
